#!/bin/bash

get1 () {
	echo $1
}

killps () {
	LINE=$(ps ax | grep $1 | grep -v "grep")
	a=$(get1 $LINE )
	if [ $a ]; then
		kill $a	
	else
		echo Can\'t find \"$1\"
	fi
}

killps julius
killps hear.py
killps answer.py

